# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JDCore' do
 
pod 'JDCore', :path => '../'

#https://github.com/wangjindong/JDRouter
pod 'JDRouter'

end
